version: '3.4'

services:
  dilbertbot:
    image: dilbertbot
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./database:/Bot/database
    environment:
      - TOKEN=<TOKEN>
      - PREFIX=^
    restart: always
